2024-01-19 19:55:12,939 ERROR: Exception on /api/v1.0/users/1 [GET] [in /home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algoar/Documents/M12/wannapop/api/users.py", line 27, in get_user
    if '_User__password' in user_dict:
    ^^^^^^^^^^
AttributeError: 'User' object has no attribute 'pop'
2024-01-19 19:55:16,597 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:55:16,601 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:55:16,601 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:55:20,049 DEBUG: <User 1> [in /home/algoar/Documents/M12/wannapop/api/users.py:24]
2024-01-19 19:55:20,049 DEBUG: <User 1> [in /home/algoar/Documents/M12/wannapop/api/users.py:24]
2024-01-19 19:56:36,915 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:56:36,920 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:56:36,920 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:57:01,549 DEBUG: <User 1> [in /home/algoar/Documents/M12/wannapop/api/users.py:26]
2024-01-19 19:57:01,549 DEBUG: <User 1> [in /home/algoar/Documents/M12/wannapop/api/users.py:26]
2024-01-19 19:57:09,923 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:57:09,928 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:57:09,928 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:58:21,610 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:58:21,614 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 19:58:21,614 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:03:46,182 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:03:46,187 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:03:46,187 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:04:03,231 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:04:03,236 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:04:03,236 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:04:53,969 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:04:53,974 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:04:53,974 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:05:11,002 DEBUG: <User 1> [in /home/algoar/Documents/M12/wannapop/api/users.py:30]
2024-01-19 20:05:11,002 DEBUG: <User 1> [in /home/algoar/Documents/M12/wannapop/api/users.py:30]
2024-01-19 20:14:22,762 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:14:22,766 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:14:22,766 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:14:38,996 ERROR: Exception on /api/v1.0/users/1/products [GET] [in /home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_user_products() got an unexpected keyword argument 'id'
2024-01-19 20:14:38,996 ERROR: Exception on /api/v1.0/users/1/products [GET] [in /home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algoar/Documents/M12/.venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_user_products() got an unexpected keyword argument 'id'
2024-01-19 20:15:18,505 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:15:18,510 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:15:18,510 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:15:18,697 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:15:18,702 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:15:18,702 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:17:03,924 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:17:03,929 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:17:03,929 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:17:04,119 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:17:04,123 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:17:04,123 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:23,815 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:23,820 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:23,820 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:31,083 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:31,088 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:31,088 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:39,358 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:39,362 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:39,362 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:40,603 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:40,608 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:40,608 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:53,132 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:53,137 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:18:53,137 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:19:51,655 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:19:51,660 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:19:51,660 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:20:00,951 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:20:00,956 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:20:00,956 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
2024-01-19 20:20:16,277 INFO: Aplicació iniciada [in /home/algoar/Documents/M12/wannapop/__init__.py:62]
